config/routes.rb
Rails.application.routes.draw do
  resources :lists do
    resources :list_items, shallow: true
  end
  resources :list_items
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/list.rb
class List < ApplicationRecord
  has_many :list_items
  has_many :note_items
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list
end

app/models/note_item.rb
class NoteItem < ListItem
end

app/models/todo_item.rb
class TodoItem < ListItem

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def new
    @item_type_options = [["todo","TodoItem"], ["note","NoteItem"]]
    @list = List.find(params[:list_id])
    @list_item = @list.list_items.new
  end
  def create
    @list = List.find(params[:list_id])
    @list_item = @list.list_items.new(list_item_params)
    if @list_item.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  def show
    @list_item = ListItem.find(params[:id])
  end

  def edit
    @list_item = ListItem.find(params[:id])
    @list = List.find(@list_item.list_id)
    @item_list_options = List.all.map{ |list| [list.title, list.id] }
  end
  def update
    if list_item_params[:checked]
      @list_item = TodoItem.find(params[:id])
      @list_item.checked = list_item_params[:checked]
      puts @list_item.checked
      puts "..........."
    else
      @list_item = ListItem.find(params[:id])
      @list_item.update(list_item_params)
    end


    if @list_item.save
      puts @list_item.checked
      puts "******"
      redirect_to root_path
    end
  end

  private
  def list_item_params
    params.require(:list_item).permit(:type, :content, :list_id, :checked)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def new
    @list = List.new
  end
  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  private
  def list_params
    params.require(:list).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trellosim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/list_items/_list_item.html.erb
<div class="list-item">
    
    <turbo-frame id=<%="edit_item_#{list_item.id}_from_#{list_item.list_id}"%>>
        <% if list_item.type=="TodoItem" %>
            <%= form_with scope: :list_item, model: list_item, url: list_item_path(list_item), method: :patch, data: {turbo_frame: "lists_container"} do |form| %>
                <div class="checkbox-item">
                    <%= form.check_box(:checked, {onchange: "this.form.requestSubmit()"}) %>
                    <li class="no-style-li"><%= link_to list_item.content, edit_list_item_path(list_item) %></li>
                </div>
            <% end%>
        <% else %>
            <li class="no-style-li"><%= link_to list_item.content, edit_list_item_path(list_item) %></li>
        <% end %>
        <div class="flex-container">
            <% if prev_list %>
                <%= form_with scope: :list_item, model: list_item, url: list_item_path(list_item), method: :patch do |form| %>
                    <%= form.hidden_field :list_id, value: prev_list.id %>
                    <%= form.submit "<-", data: {turbo_frame: "lists_container"}%>
                <% end %>
            <% end %>
            <% if next_list %>
                <%= form_with scope: :list_item, model: list_item, url: list_item_path(list_item), method: :patch do |form| %>
                    <%= form.hidden_field :list_id, value: next_list.id %>
                    <%= form.submit "->", data: {turbo_frame: "lists_container"}%>
                <% end %>
            <% end %>
        </div>
    </turbo-frame>
    
</div>
<br>

app/views/list_items/_list_item_simple.html.erb
<div class="list-item"> 
    <turbo-frame id=<%="edit_item_#{list_item.id}_from_#{list_item.list_id}"%>>
        <li><%= link_to list_item.content, edit_list_item_path(list_item) %></li>
    </turbo-frame> 
</div>
<br>

app/views/list_items/edit.html.erb
<turbo-frame id=<%="edit_item_#{@list_item.id}_from_#{@list.id}"%>>
<%= form_for [@list, @list_item], url: list_item_path, method: :patch do |form| %>
    <%= form.text_field :content %> 
    <br />
    <%= form.label :list_id, "Move to"%>
    <%= form.select(:list_id, @item_list_options) %> 
    <br />
    <%= form.submit "Save", data: {turbo_frame: "_top"}%>
<% end %>
</turbo-frame>

app/views/list_items/new.html.erb
<turbo-frame id=<%="add_to_list_#{@list.id}"%>>
    Add Item to List
    <div class="form">
        <%= form_for [@list, @list_item] do |form| %>
            <%= form.label :type %>
            <%= form.select(:type, @item_type_options) %>
            <br />
            <%= form.label :content %>
            <%= form.text_field :content %>
            <br />
            <%= form.submit "Add", data: {turbo_frame: "list_#{@list.id}"} %>
        <% end %>
    </div>
</turbo-frame>

app/views/list_items/show.html.erb
<%= render partial: "list_item_simple", locals: {list_item: @list_item}%>

app/views/lists/_list.html.erb
<turbo-frame id=<%="list_#{list.id}"%>>
    <strong><%= list.title %></strong>
    <br>
    <% prev_list = List.where("id < ?", list.id).last %>
    <% next_list = List.where("id > ?", list.id).first %>
    <ul>
        <% list.list_items.order("updated_at ASC").each do |list_item| %>
            <%= render partial: "list_items/list_item", locals: {list_item: list_item, prev_list: prev_list, next_list: next_list} %>
        <% end %>
    </ul>    
    <turbo-frame id=<%="add_to_list_#{list.id}"%>>
        <%= button_to "Add Item", new_list_list_item_path(list), method: :get %>
    </turbo-frame>
</turbo-frame>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<%= link_to "New List", new_list_path %>
<br>
<turbo-frame id="lists_container">
    <div class="lists-container">
        <% @lists.each do |list| %>
            <%= render partial: "list", locals: {list: list} %>
        <% end %>
    </div>
</turbo-frame>

app/views/lists/new.html.erb
Create New List
<%= form_with model: @list do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <%= form.submit "Create" %>
<% end %>

app/views/lists/show.html.erb
<%= render partial: "list", locals: {list: @list} %>